language: julia
julia:
- 0.7
- 1.0
- nightly
matrix:
  allow_failures:
    - julia: nightly
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("LeastSquaresOptim")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  email: false
  on_success: never 
  on_failure: change